email = "warunaoshan@gmail.com"
# facebook = "yourfacebookusername"
github = "oshanz"
gitlab = "oshanw"
linkedin = "in/oshanz"
stackoverflow = "3011280/oshan-wisumperuma"
twitter = "oshanz"
# weibo = "yourweibousername"
# zhihu = "yourzhihuusername"
instagram = "oshan.w"
# quora = "yourquorausername"
# tumblr = "yourtumblrusername"
reddit = "oshanz"
# telegram = "yourtelegramusername"
# qq = "yourqqnumber"
# dockerhub = "yourdockerhubusername"
# bitbucket = "oshanz"
# kaggle = "yourkaggleusername"
# medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm = "yourlastfmusername"
# bilibili = "yourbilibiliuserid"
# youtube = "youryoutubechannelid"
# discord = "Oshan Wisumperuma#0575"
# discourse = "https://yourforum.tld"
# facebookgroup = "yourfacebookgroupname"
# tiktok = "yourtiktokusername"
