baseURL = ''
languageCode = 'en-us'
title = 'site under construction'
theme = "hugo-theme-console"
# layout="index.html"

[params]
description = "Oshan Wisumperuma"
animateStyle = "animate-fade-up" # Animation style for content

[[params.navlinks]]
name = "About"
url = "/about/"

[[params.navlinks]]
name = "Posts"
url = "/posts/"

[[params.navlinks]]
name = "Photos"
url = "/photos/"
